# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c10e6cf9c66625ab6f949afe371bb6cc2fdaed1cdb7a574415d7ea7f73f408dd16c17eb6bec93ec9bbe79d61fdf25bb03ace280abe01ca39272e33846f549c9

test:
  secret_key_base: c6a1d2ebb61a7f375452100c934730f3c83ed126b02c3f9057dd5bc98b38daaca3ba4438396c3791b28df9de77a103808113a412d359e92562cf3d58ea1ec30e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
